server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  
  # OAuth2 Resource Server - Keycloak JWT Validation
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SecureHeaders=X-Content-Type-Options,X-Frame-Options,Strict-Transport-Security
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
                allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600
          routes:
            - id: auth-ms
              uri: lb://auth-ms
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=0
            - id: business-ms
              uri: lb://business-ms
              predicates:
                - Path=/api/business/**
              filters:
                - StripPrefix=0
            - id: invoice-ms
              uri: lb://invoice-ms
              predicates:
                - Path=/api/invoices/**
              filters:
                - StripPrefix=0
            - id: expense-ms
              uri: lb://expense-ms
              predicates:
                - Path=/api/expense/**
              filters:
                - StripPrefix=0
            - id: client-ms
              uri: lb://client-ms
              predicates:
                - Path=/api/client/**
              filters:
                - StripPrefix=0
            - id: reporting-ms
              uri: ${REPORTING_MS_URL:http://reporting-ms:8000}
              predicates:
                - Path=/api/reporting/**
              filters:
                - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      circuitbreaker:
        resilience4j:
          configs:
            default:
              failureRateThreshold: 50
              waitDurationInOpenState: 30s
              slidingWindowSize: 10
              slidingWindowType: COUNT_BASED
          instances:
            auth-ms:
              baseConfig: default
            business-ms:
              baseConfig: default
            invoice-ms:
              baseConfig: default
            expense-ms:
              baseConfig: default
            client-ms:
              baseConfig: default

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: when_authorized
    gateway:
      access: unrestricted
  health:
    defaults:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
