server:
  port: 8080

spring:
  application:
    name: api-gateway
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  gateway:
    jwt:
      secret: ${SECURITY_JWT_SECRET:changeitchangeitchangeitchangeit}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RequestHeaderToRequestUri=X-Forwarded-Host, X-Forwarded-Proto
          routes:
            - id: auth-ms
              uri: ${AUTH_MS_URL:http://auth-ms:8081}
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
            - id: business-ms
              uri: ${BUSINESS_MS_URL:http://business-ms:8080}
              predicates:
                - Path=/api/business/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 40
            - id: invoice-ms
              uri: ${INVOICE_MS_URL:http://invoice-ms:8080}
              predicates:
                - Path=/api/invoices/**
                - Path=/api/health
              filters:
                - StripPrefix=1
            - id: expense-ms
              uri: ${EXPENSE_MS_URL:http://expense-ms:8080}
              predicates:
                - Path=/api/expense/**
              filters:
                - StripPrefix=1
            - id: client-ms
              uri: ${CLIENT_MS_URL:http://client-ms:8080}
              predicates:
                - Path=/api/client/**
              filters:
                - StripPrefix=1
            - id: reporting-ms
              uri: ${REPORTING_MS_URL:http://reporting-ms:8000}
              predicates:
                - Path=/api/reporting/**
              filters:
                - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
