spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/accountia}
    username: ${SPRING_DATASOURCE_USERNAME:accountia}
    password: ${SPRING_DATASOURCE_PASSWORD:accountia}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:changeitchangeitchangeitchangeit}
    expiration-ms: ${SECURITY_JWT_EXPIRATION_MS:3600000}
